export const mockJobs = [
  {
    id: '1',
    title: 'Frontend Engineer',
    company: 'Stripe',
    company_logo: 'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=80&h=80&fit=crop&auto=format',
    location: 'San Francisco, CA',
    salary: '$120k – $160k',
    salary_min: 120000,
    salary_max: 160000,
    description: "Join Stripe's frontend team to build the financial infrastructure of the internet. You'll work on high-impact products used by millions of businesses worldwide. We're looking for engineers who care deeply about developer experience and pixel-perfect UIs.",
    skills: ['React', 'TypeScript', 'CSS', 'GraphQL', 'Next.js'],
    requirements: [
      '3+ years of frontend experience',
      'Strong TypeScript skills',
      'Experience with React and modern tooling',
      'Attention to detail and design sensibility',
      'Experience with performance optimization',
    ],
    benefits: ['Equity', 'Remote-friendly', 'Health + Dental', '401k', 'Learning budget'],
    recruiter_id: 'r1',
    type: 'full-time',
    category: 'Engineering',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    title: 'Product Design Intern',
    company: 'Figma',
    company_logo: 'https://images.unsplash.com/photo-1547658719-da2b51169166?w=80&h=80&fit=crop&auto=format',
    location: 'Remote',
    salary: '$45/hr',
    description: "Help shape the future of design tools at Figma. You'll work directly with senior designers on core product features and ship work seen by millions of designers.",
    skills: ['Figma', 'Prototyping', 'User Research', 'Design Systems'],
    requirements: [
      'Currently pursuing a degree in Design or HCI',
      'Portfolio showing strong visual and interaction work',
      'Proficiency in Figma',
    ],
    benefits: ['Flexible hours', 'Mentorship', 'Full-time offer potential'],
    recruiter_id: 'r2',
    type: 'internship',
    category: 'Design',
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    title: 'Backend Engineer – Payments',
    company: 'Razorpay',
    company_logo: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=80&h=80&fit=crop&auto=format',
    location: 'Bangalore, IN',
    salary: '₹18L – ₹28L',
    description: "Scale payment infrastructure that powers India's digital economy. Work on distributed systems processing millions of transactions daily with strict reliability and security requirements.",
    skills: ['Go', 'PostgreSQL', 'Redis', 'Kafka', 'Docker'],
    requirements: [
      '2+ years backend experience',
      'Strong systems design fundamentals',
      'Experience with high-throughput services',
    ],
    benefits: ['ESOPs', 'Comprehensive health coverage', 'Learning stipend'],
    recruiter_id: 'r3',
    type: 'full-time',
    category: 'Engineering',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    title: 'Data Science Intern',
    company: 'Swiggy',
    company_logo: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=80&h=80&fit=crop&auto=format',
    location: 'Hyderabad, IN',
    salary: '₹30k/month',
    description: 'Apply ML to optimize food delivery logistics, demand forecasting, and personalization at scale for 10M+ daily orders.',
    skills: ['Python', 'PyTorch', 'SQL', 'Pandas', 'Scikit-learn'],
    requirements: [
      'Pursuing BTech/MTech in CS or related field',
      'Strong probability and statistics foundation',
      'At least one ML project in portfolio',
    ],
    benefits: ['Food credit', 'Hybrid work', 'Return offer potential'],
    recruiter_id: 'r4',
    type: 'internship',
    category: 'Data Science',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    title: 'Full Stack Developer',
    company: 'Linear',
    company_logo: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=80&h=80&fit=crop&auto=format',
    location: 'Remote',
    salary: '$130k – $170k',
    description: "Build the issue tracking tool loved by the world's best software teams. Linear values craft, speed, and simplicity in everything we build.",
    skills: ['TypeScript', 'React', 'Node.js', 'GraphQL', 'PostgreSQL'],
    requirements: [
      '5+ years full-stack experience',
      'Extreme attention to product quality',
      'Experience with real-time collaboration systems',
    ],
    benefits: ['Fully remote', 'Async-first culture', 'Equity', 'Equipment budget'],
    recruiter_id: 'r5',
    type: 'full-time',
    category: 'Engineering',
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    company: 'CRED',
    company_logo: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=80&h=80&fit=crop&auto=format',
    location: 'Bangalore, IN',
    salary: '₹20L – ₹32L',
    description: "Own infrastructure for one of India's fastest-growing fintech companies. Build reliable, scalable systems for millions of CRED members.",
    skills: ['Kubernetes', 'AWS', 'Terraform', 'CI/CD', 'Python'],
    requirements: [
      '3+ years DevOps/SRE experience',
      'Strong Kubernetes knowledge',
      'Experience with fintech or high-scale systems',
    ],
    benefits: ['ESOPs', 'Premium health insurance', 'CRED coins'],
    recruiter_id: 'r6',
    type: 'full-time',
    category: 'DevOps',
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
]

export const mockApplications = [
  { id: 'a1', student_id: 'u1', job_id: '1', status: 'interview', created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), job: mockJobs[0] },
  { id: 'a2', student_id: 'u1', job_id: '2', status: 'reviewing', created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), job: mockJobs[1] },
  { id: 'a3', student_id: 'u1', job_id: '4', status: 'applied', created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), job: mockJobs[3] },
  { id: 'a4', student_id: 'u1', job_id: '3', status: 'accepted', created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), job: mockJobs[2] },
]

export const mockRecruiterApplicants = [
  {
    id: 'ap1', student_id: 's1', job_id: '1', status: 'applied',
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    job: mockJobs[0],
    profile: { id: 's1', name: 'Arjun Sharma', email: 'arjun.sharma@iitb.ac.in', role: 'student', phone: '+91 98765 43210', college: 'IIT Bombay' },
  },
  {
    id: 'ap2', student_id: 's2', job_id: '1', status: 'reviewing',
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    job: mockJobs[0],
    profile: { id: 's2', name: 'Priya Nair', email: 'priya.nair@bits.ac.in', role: 'student', phone: '+91 87654 32109', college: 'BITS Pilani' },
  },
  {
    id: 'ap3', student_id: 's3', job_id: '1', status: 'interview',
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    job: mockJobs[0],
    profile: { id: 's3', name: 'Rahul Verma', email: 'rahul.v@nit.ac.in', role: 'student', phone: '+91 76543 21098', college: 'NIT Trichy' },
  },
  {
    id: 'ap4', student_id: 's4', job_id: '1', status: 'rejected',
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    job: mockJobs[0],
    profile: { id: 's4', name: 'Sneha Patel', email: 'sneha.p@vit.ac.in', role: 'student', phone: '+91 65432 10987', college: 'VIT Vellore' },
  },
]
